# Site settings
title: XLSForm.org
email: info@xlsform.org
description: 
  en: "This site will help you author XLSForms. XLSForm is a tool used to simplify the creation of forms. XLSForm will convert forms authored in Excel into XForms that can be used with a number of web or mobile platforms."
baseurl: ""
url: "https://xlsform.org"

# Build settings
markdown: kramdown
permalink: pretty

collections:
- sections

g_analytics_token: 'UA-55713660-1'
g_analytics_domain: 'xlsform.org'

kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]